version: "3.7"
services:
  proyectos-micros :
    container_name: proyectos-micros
    image: proyectos-micros:v1
    build:
      context: .
    ports:
      - "4001"
    networks:  
      - proyectos-app     

  proyectos-micros-2 :
    container_name:  proyectos-micros-2
    image: proyectos-micros:v1
    ports:
      - "4001"
    networks:  
      - proyectos-app 

  proyectos-micros-3 :
    container_name: proyectos-micros-3
    image: proyectos-micros:v1
    ports:
      - "4001"
    networks:  
      - proyectos-app    

  loader-balancer :  
    container_name: loader-balancer
    image: loader-balancer
    build:
      context: ./loader-balancer
    ports:
      - "4003:80"
    networks:  
      - proyectos-app  
    depends_on:
        - proyectos-micros
        - proyectos-micros-2
        - proyectos-micros-3


networks:
  proyectos-app: